Ano3/SIO/assignment-1---vulnerable-ehealth-application-grupo_18_/app/website/auth.py
from flask import Blueprint,render_template,request,flash,redirect,url_for
from .forms import PostForm,RequestResetForm,ResetPasswordForm
from .models import User
from . import db
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user,login_required,logout_user,current_user
from .__init__ import Mail
from flask_mail import Message
from flask import current_app

auth = Blueprint('auth',__name__)

@auth.route ('/index',methods=['GET','POST'])
def index():
    return render_template("index.html",user=current_user)

@auth.route ('/login',methods=['GET','POST'])
def login():
    if request.method=='POST':
        email=request.form.get('email')
        password=request.form.get('password')
        if email=="" or password=="":
            flash('Invalid Credentials',category='error')
            return render_template("login.html", user=current_user)
        sql=f"SELECT * FROM User WHERE email='{email}' AND password='{password}'"
        
        user = User.query.from_statement(db.text(sql)).first()
        if user:
            flash('Logged in sucessfully!',category='sucess')
            login_user(user,remember=True)
            return redirect(url_for('views.home'))
        else:
            flash('Incorrect password,try again.',category='error')
    return render_template("login_healthclinic.html", user=current_user)


@auth.route ('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

@auth.route ('/register',methods=['GET','POST'])
def register():
    
    if request.method=='POST':
            email=request.form.get('email')
            full_name=request.form.get('fullname')
            password=request.form.get('password')
            repassword=request.form.get('repassword')

            user=User.query.filter_by(email=email).first()

            if user:
                flash('Email already exists.',category='error')
            elif len(email) < 4:
                flash('Email must be greater than 3 characters.', category='error')
            elif len(full_name) < 2:
                flash('First name must be greater than 1 character.', category='error')
            elif password != repassword:
                flash('Passwords don\'t match.', category='error')
            elif len(password) < 7:
                flash('Password must be at least 7 characters.', category='error')
            else:
                if email.find('/'): email.replace('/','\'')
                if email.find('-'): email.replace('-','\-')
                if email.find('"'): email.replace('-','\"')
                if full_name.find('/'): full_name.replace('/','\'')
                if full_name.find('-'): full_name.replace('-','\-')
                if full_name.find('"'): full_name.replace('-','\"')
                if password.find('/'): password.replace('/','\'')
                if password.find('-'): password.replace('-','\-')
                if password.find('"'): password.replace('-','\"')
                new_user = User(email=email,full_name=full_name,password=password)
                db.session.add(new_user)
                db.session.commit()
                login_user(new_user,remember=True)
                flash('Account created!',category='success')
                return redirect(url_for('views.home'))

    return render_template("register_healthclinic.html",user=current_user)

@auth.route ('/profile/<userid>',methods=['GET','POST'])
@login_required
def profile(userid):
    userr=User.query.get(int(userid))
    return render_template("Pessoa.html",user=userr)

@auth.route ('/funcionario2',methods=['GET','POST'])
@login_required
def funcionario2():
    if current_user.is_authenticated:
        return render_template("funcionario2.html", user=current_user)


@auth.route ('/resetpassword',methods=['GET','POST'])
def reset_password():
    if current_user.is_authenticated:
        return redirect(url_for('views.home'))
    form = ResetPasswordForm()
    user = User.query.filter_by(email=form.email.data).first()
    if user:
        if form.validate_on_submit():
            password=request.form.get('password')
            if password.find('/'): password.replace('/','\'')
            if password.find('-'): password.replace('-','\-')
            if password.find('"'): password.replace('-','\"')
            
            user.password = password
            db.session.commit()
            flash('Your password has been updated! You are now able to log in',category='success')
            return redirect(url_for('auth.login'))
    else:
        return render_template('reset_token.html',title='Reset Password',form=form,user=current_user)

@auth.route('/download')
def download():
    path = 'samplefile.pdf'
    return send_file(path, as_attachment=True)

Ano3/SIO/assignment-1---vulnerable-ehealth-application-grupo_18_/app/website/templates/Funcionario2.html
{% extends "primary.html" %} {% block title %}Funcionario2{% endblock %} {% block content%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>CliniCare™</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{{url_for('static',filename = 'assets/favicon.ico'" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" />

    <!-- Custom styles for this template-->
    <link href="{{url_for('static',filename = 'css/sb-admin-2.css')}}" rel="stylesheet">

    <!-- Core theme CSS (includes Bootstrap)-->
    <link rel="stylesheet" href="{{url_for('static', filename='css/styles.css')}}" />
    <link rel="stylesheet" href="{{url_for('static', filename='css/style2.css')}}" />
    <link href="{{url_for('static',filename = 'css/chat.css')}}" rel="stylesheet" />


    <meta charset="UTF-8">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
    <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Open+Sans'>
    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.3/jquery.mCustomScrollbar.min.css'>

</head>

<body class="space">

    <!-- Navigation-->
    <nav class="navbar navbar-expand-md navbar-dark fixed-top" id="mainNav">
        <div class="container">
            <a class="navbar-brand" href="{{ url_for('auth.index') }}">CliniCare™</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                Menu
                <i class="fas fa-bars ms-1"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav text-uppercase ms-auto py-4 py-lg-0">

                    <li class="nav-item"><a class="nav-link" href="{{ url_for('auth.index') }}#about">About</a></li>
                    <li class="nav-item"><a class="nav-link" href="{{ url_for('auth.index') }}#contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">

        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-6">
                    <div class="card-body p-4">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <div class="col-lg-6 d-none d-lg-block">
                                <img class="" src="{{url_for('static', filename='assets/img/team/2.jpg')}}" alt="..." />
                            </div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h1 text-warning mb-5">
                                            Diana Petersen
                                        </h1>
                                    </div>
                                    <div class="form-group row">
                                        <div class="col-sm-6 mb-4 h6 text-gray-900 mb-3">
                                            Profissão:
                                        </div>
                                        <div class="col-sm-6">
                                            Médica
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <div class="col-sm-6 mb-4 h6 text-gray-900 mb-3">
                                            Email:
                                        </div>
                                        <div class="col-sm-6">
                                            DianaPetersen@ua.pt
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <div class="col-sm-6 mb-4 h6 text-gray-900 mb-3">
                                            Graduated the University of:
                                        </div>
                                        <div class="col-sm-6">
                                            LA Médica
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <div class="col-sm-6 mb-4 h6 text-gray-900 mb-3">
                                            Data de nascimento:
                                        </div>
                                        <div class="col-sm-6">
                                            5-12-2002
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <div class="col-sm-3 mb-4 h6 text-gray-900 mb-3">
                                            Rating:
                                        </div>

                                    </div>
                                    <div class="form-group row">
                                        <a class="btn btn-outline-success btn-xl text-uppercase joao" onclick="openForm()" id="btnchat">Chat</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>


            </div>

        </div>

    </div>

    <div class="form-popup1" id="myForm">
        <div class="container">

            <div class="chat">
                <div class="chat-title">
                    <h1>Diana Petersen</h1>
                    <button class="btn_close2" onclick="closeForm()" id="sairchat">_</button>

                    <figure class="avatar">
                        <img src="assets/img/team/2.jpg" alt="">
                    </figure>
                </div>
                <div class="messages">
                    <div class="messages-content"></div>
                </div>
                <div class="message-box">
                    <textarea type="text" class="message-input" placeholder="Escreva a mensagem..." id="textchat"></textarea>
                    <button type="submit" class="message-submit" id="enviar-chat">Enviar</button>
                </div>
            </div>

        </div>

        <script>
            function openForm() {
                document.getElementById("myForm").style.display = "block";
            }

            function closeForm() {
                document.getElementById("myForm").style.display = "none";
            }
        </script>
        <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
        <script src='https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.3/jquery.mCustomScrollbar.concat.min.js'></script>
        <script src="js/chat.js"></script>

        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>

        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>

</body>

</html>
{% endblock %}

Ano3/SIO/assignment-1---vulnerable-ehealth-application-grupo_18_/app/website/templates/Pessoa.html
{% extends "primary.html" %} {% block title %}Profile{% endblock %} {% block content %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>CliniCare™</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{{url_for('static', filename='assets/favicon.ico')}}" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" />

    <!-- Custom styles for this template-->
    <link href="{{url_for('static', filename='css/sb-admin-2.css')}}" rel="stylesheet">

    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{{url_for('static', filename = 'css/styles.css')}}" rel="stylesheet" />
    <link href="{{url_for('static', filename='css/style2.css')}}" rel="stylesheet" />
</head>

<body class="bg-gradient-success">
    <div class="container">
        <!-- Outer Row -->
        <div class="row justify-content-center">
            <div class="col-xl-10 col-lg-12 col-md-9">
                <div class="card o-hidden border-0 shadow-lg my-6">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <div class="col-lg-6 d-none d-lg-block">
                                <img class="" src="../static/assets/img/team/1.jpg" id="imgPrevie" width="100%" height="100%" alt="Preview" />
                            </div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h1 text-warning mb-5" id="full_name">
                                        </h1>
                                    </div>
                                    <div class="form-group row">
                                        <div>
                                            <text class="col-sm-6 mb-4 h6 text-gray-900 mb-3">Name:</text>
                                            <text class="col-sm-6">
                                                {{ user.full_name }}
                                            </text>
                                            <p></p>
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <div>
                                            <text class="col-sm-6 mb-4 h6 text-gray-900 mb-3">Phone:</text>
                                            <text class="col-sm-6">
                                                958 685 988
                                            </text>
                                            <p></p>
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <div>
                                            <text class="col-sm-6 mb-4 h6 text-gray-900 mb-3">Email:</text>
                                            <text class="col-sm-6">
                                                {{ user.email }}
                                            </text>
                                            <p></p>
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <div>
                                            <text class="col-sm-4 mb-4 h6 text-gray-900 mb-3">
                                                Change Photo:
                                            </text>
                                            <p></p>
                                        </div>
                                        <div>
                                            <div class="col-sm-7" id="pet_pic">
                                                <a class="btn btn-primary btn-user btn-block" id="button_">
                                                    <input type="file" id="myFileInput" style="display:none;">
                                                    <label for="myFileInput">Choose image</label>

                                                </a>

                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

</html>

{% endblock %}

Ano3/SIO/assignment-1---vulnerable-ehealth-application-grupo_18_/app/website/templates/home.html
{% extends "primary.html" %} {% block title %}Home{% endblock %} {% block content%}

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>CliniCare™</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{{url_for('static',filename = 'assets/icons8-heart-health-64')}}" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" />

    <!-- Custom styles for this template-->
    <link href="{{url_for('static', filename = 'css/sb-admin-2.css')}}" rel="stylesheet">

    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{{url_for('static', filename = 'css/styles.css')}}" rel="stylesheet" />
    <link href="{{url_for('static', filename = 'css/style2.css')}}" rel="stylesheet" />


</head>

<form action="/search" class="form-inline my-2 my-lg-0" method="GET">
    <input class="form-control mr-sm-2" type="search" placeholder="Pesquisa" name='q'>
    <button class="btn btn-outline-sucess my-2 my-sm-0" type="submit"><i class="fa fa-search"></i></button>
</form>

<br />
<div class="row">
    <a href="#newModal" data-toggle="modal" class="btn btn-primary" title="New publication">
        <i class="glyphicon glyphicon-plus-sign"></i> Perguntas
    </a>
</div>

<br />
<div class="pageTitle" align="center">
    <h1>Resultados</h1>
</div>
<br />
<div class="row pad">
    <div class="col-lg-12">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-lg-4">
                        <font size="+2">Titulo</font>
                    </div>
                    <div class="col-lg-4">
                        <font size="+2">Descrição</font>
                    </div>
                    <div class="col-lg-4">
                        <font size="+2">Data</font>
                    </div>
                </div>
            </div>
            {% for publication in publications %}
            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-4">
                        <h3 class="panel-title">
                            <font size="+2">
                                <a href="{{ url_for('views.publication', publication_id=publication.id) }}" style="font-size: 18px;" class="blue text-decoration-none">
                                {{ publication.title }}
                            </a>
                            </font>
                        </h3>
                    </div>
                    <div class="col-lg-4">
                        <font size="+1">
                            <p>
                                <em>
                                {{ publication.description }}
                            </em>
                            </p>
                        </font>
                    </div>

                    <div class="col-lg-4">
                        <i class="glyphicon glyphicon-calendar"></i>
                        <font size="+1">{{ publication.lastDate().strftime('%d %B, %Y') }} &nbsp;</font>

                        <a href="{{ url_for('views.publication', publication_id=publication.id) }}">
                            <i class="glyphicon glyphicon-comment"></i> Descarregar
                        </a>
                    </div>
                </div>

            </div>
            {% endfor %}
        </div>
    </div>
</div>

<div class="modal fade" id="newModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Pergunta-nos</h4>
            </div>
            <div class="modal-body">
                <form method="POST" role="form">
                    {{ form.csrf_token }}
                    <div class="form-group">
                        {{ form.title(class="form-control", placeholder="Assunto") }}
                        <br />
                    </div>
                    <div class="form-group">
                        {{ form.description(class="form-control", placeholder="Mensagem") }}
                        <br />
                    </div>

                    <button type="submit" class="btn btn-primary">Enviar</button>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
            </div>
        </div>
    </div>
</div>
</form>

{% endblock %}

Ano3/SIO/assignment-1---vulnerable-ehealth-application-grupo_18_/app/website/templates/login_healthclinic.html
{% extends "primary.html" %}{% block title %}Login{% endblock %} {% block content %}
<form method="POST">
    <!DOCTYPE html>
    <html lang="en">

    <head>
        <meta charset="UTF-8">
        <title>Login</title>
        <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/css/bootstrap.min.css'>
        <link rel='stylesheet' href='https://unicons.iconscout.com/release/v2.1.9/css/unicons.css'>
        <link href="{{url_for('static', filename = 'css/styles.css')}}" rel="stylesheet" />
        <link rel="stylesheet" href="{{url_for('static', filename='css/style2.css')}}">
    </head>

    <body>
        <!-- partial:index.partial.html -->
        <div class="section">
            <div class="container">
                <div class="row full-height justify-content-center">
                    <div class="col-12 text-center align-self-center py-5">
                        <div class="section pb-5 pt-5 pt-sm-2 text-center">
                            <h6 class="mb-0 pb-3"><span>Clique aqui</span></h6>
                            <input class="checkbox" type="checkbox" id="reg-log" name="reg-log" />
                            <label for="reg-log"></label>
                            <div class="card-3d-wrap mx-auto">
                                <div class="card-3d-wrapper">
                                    <div class="card-front">
                                        <div class="center-wrap">
                                            <div class="section text-center">
                                                <h4 class="mb-4 pb-3">Entrar</h4>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="card-back">
                                        <!---->
                                        <div class="center-wrap">
                                            <div class="section text-center">
                                                <h4 class="mb-4 pb-3">Entrar</h4>

                                                <div class="form-group">
                                                    <input name="email" class="form-style" placeholder="Your Email" id="email" autocomplete="on">
                                                    <i class="input-icon uil uil-at"></i>
                                                </div>
                                                <div class="form-group mt-2">
                                                    <input type="password" name="password" class="form-style" placeholder="Your Password" id="password" autocomplete="off">
                                                    <i class="input-icon uil uil-lock-alt"></i>
                                                </div>
                                                <div class="form-group mt-4">
                                                    <button class="btn btn-primary btn-block" id="login">Entrar</button>
                                                </div>
                                                <small class="text-muted ml-2">
													<a href="{{ url_for('auth.reset_password') }}">Esqueceu-se da palavra passe</a>
												</small>
                                            </div>
                                        </div>
                                    </div>
                                    <!---->

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- partial -->
        <script src="./js/script2.js"></script>

    </body>

    </html>

</form>
{% endblock %}

Ano3/SIO/assignment-1---vulnerable-ehealth-application-grupo_18_/app/website/templates/primary.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device_width,initial-scale=1" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.15.4/css/fontawesome.min.css" integrity="sha384-jLKHWM3JRmfMU0A5x5AkjWkw/EYfGUAGagvnfryNV3F9VqM98XiIH7VBGVoxVSc7" crossorigin="anonymous" />
    <title>{% block title %}{% endblock %}</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar">
                <span class = "navbar-toggler-icon"></span>
            </button>
        <div class="collapse navbar-collapse" id="navbar">
            <div class="navbar-nav">
                <a class="nav-item nav-link" id="home" href="/index">CliniCare™</a> {% if user.is_authenticated %}
                <a class="nav-item nav-link" id="home" href="/">Resultados</a>
                <a class="nav-item nav-link" id="profile" href="{{ url_for('auth.profile', userid=user.id) }}">Perfil
                    </a>
                <a class="nav-item nav-link" id="logout" href="/logout">Sair</a> {% else %}
                <!-- <a class ="nav-item nav-link" id="home" href="/">CliniCare™</a> -->
                <a class="nav-item nav-link" id="login" href="/login">Entrar</a>
                <a class="nav-item nav-link" id="register" href="/register">Registrar</a> {% endif %}
            </div>
        </div>
    </nav>
    {% with messages = get_flashed_messages(with_categories=true) %} {% if messages %} {% for category, message in messages %} {% if category == 'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert">
                <span aria-hidden="true">&times;</span>
            </button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert">
                    <span aria-hidden="true">&times;</span>
                </button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}

    <div class="container">{% block content %} {%endblock %}
    </div>


    <script src="https://code.jquery.com/jquery-3.6.0.slim.min.js" integrity="sha256-u7e5khyithlIdTpu22PHhENmPcRdFiHRjhAuHcs05RI=" crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.10.2/umd/popper.min.js" integrity="sha512-nnzkI2u2Dy6HMnzMIkh7CPd1KX445z38XIu4jG1jGw7x5tSL3VBjE44dY4ihMU1ijAQV930SPM12cCFrB18sVw==" crossorigin="anonymous" referrerpolicy="no-referrer">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous">
    </script>

    <script type="text/javascript" src="{{ url_for('static', filename='index.js') }}"></script>
</body>

</html>

</html>